// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMkjxJcfxWydEXYdzk2MRqvJ3d5R6rPU',
    appId: '1:46674278567:web:3c80ade54e806856f68382',
    messagingSenderId: '46674278567',
    projectId: 'e-trade-actions',
    authDomain: 'e-trade-actions.firebaseapp.com',
    storageBucket: 'e-trade-actions.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuyvgjns9i6ux9mvtKheqvr685ChxOp7A',
    appId: '1:46674278567:android:2af7662410c09f0bf68382',
    messagingSenderId: '46674278567',
    projectId: 'e-trade-actions',
    storageBucket: 'e-trade-actions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxC-8-JLOpnmeeY9N29UF9VJSwiHPld3E',
    appId: '1:46674278567:ios:265b032d5bdaeeecf68382',
    messagingSenderId: '46674278567',
    projectId: 'e-trade-actions',
    storageBucket: 'e-trade-actions.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxC-8-JLOpnmeeY9N29UF9VJSwiHPld3E',
    appId: '1:46674278567:ios:20c85e83f35a9447f68382',
    messagingSenderId: '46674278567',
    projectId: 'e-trade-actions',
    storageBucket: 'e-trade-actions.appspot.com',
    iosBundleId: 'com.example.etradeActions.RunnerTests',
  );
}
